title: petrosh
baseurl:
description: Raw minimal theme for Jekyll
permalink: pretty
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      menu: 0
js:
  - menu
css:
  - style
colors:
  - link_color: "#b33"
  - grey_color: "#7f7f7f"
