title: petrosh
baseurl:
description: Raw minimal theme for Jekyll
permalink: pretty
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
js:
  - menu
css:
  - style
